export const developers = [
  {
    rank: 1,
    username: 'nunomaduro',
    name: 'Nuno Maduro',
    url: 'https://github.com/nunomaduro',
    avatar: 'https://avatars.githubusercontent.com/u/5457236?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'termwind',
      description:
        "🍃In short, it's like Tailwind CSS, but for the PHP command-line applications.",
      url: 'https://github.com/nunomaduro/termwind',
    },
  },
  {
    rank: 2,
    username: 'felixonmars',
    name: 'Felix Yan',
    url: 'https://github.com/felixonmars',
    avatar: 'https://avatars.githubusercontent.com/u/1006477?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'archriscv-packages',
      description: 'Modified Arch Linux packages for archriscv',
      url: 'https://github.com/felixonmars/archriscv-packages',
    },
  },
  {
    rank: 3,
    username: 'gakonst',
    name: 'Georgios Konstantopoulos',
    url: 'https://github.com/gakonst',
    avatar: 'https://avatars.githubusercontent.com/u/17802178?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'ethers-rs',
      description:
        'Complete Ethereum & Celo library and wallet implementation in Rust.https://docs.rs/ethers',
      url: 'https://github.com/gakonst/ethers-rs',
    },
  },
  {
    rank: 4,
    username: 'atapas',
    name: 'Tapas Adhikary',
    url: 'https://github.com/atapas',
    avatar: 'https://avatars.githubusercontent.com/u/3633137?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'webapis-playground',
      description:
        'The Web APIs Playground is a project to showcase the JavaScript Web APIs with examples and demonstrations. Client-side JavaScript APIs are here to help with providing wrapper functions for many low-level tasks.',
      url: 'https://github.com/atapas/webapis-playground',
    },
  },
  {
    rank: 5,
    username: 'tiangolo',
    name: 'Sebastián Ramírez',
    url: 'https://github.com/tiangolo',
    avatar: 'https://avatars.githubusercontent.com/u/1326112?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'fastapi',
      description:
        'FastAPI framework, high performance, easy to learn, fast to code, ready for production',
      url: 'https://github.com/tiangolo/fastapi',
    },
  },
  {
    rank: 6,
    username: 'hathach',
    name: 'Ha Thach',
    url: 'https://github.com/hathach',
    avatar: 'https://avatars.githubusercontent.com/u/249515?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'tinyusb',
      description:
        'An open source cross-platform USB stack for embedded system',
      url: 'https://github.com/hathach/tinyusb',
    },
  },
  {
    rank: 7,
    username: 'alex',
    name: 'Alex Gaynor',
    url: 'https://github.com/alex',
    avatar: 'https://avatars.githubusercontent.com/u/772?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'what-happens-when',
      description:
        'An attempt to answer the age old interview question "What happens when you type google.com into your browser and press enter?"',
      url: 'https://github.com/alex/what-happens-when',
    },
  },
  {
    rank: 8,
    username: 'StorytellerCZ',
    name: 'Jan Dvorak',
    url: 'https://github.com/StorytellerCZ',
    avatar: 'https://avatars.githubusercontent.com/u/1715235?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 9,
    username: 'adiwajshing',
    name: 'Adhiraj Singh',
    url: 'https://github.com/adiwajshing',
    avatar: 'https://avatars.githubusercontent.com/u/8328864?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'Baileys',
      description:
        'Lightweight full-featured typescript/javascript WhatsApp Web API',
      url: 'https://github.com/adiwajshing/Baileys',
    },
  },
  {
    rank: 10,
    username: 'chrisleekr',
    name: 'chrisleekr',
    url: 'https://github.com/chrisleekr',
    avatar: 'https://avatars.githubusercontent.com/u/5715919?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'binance-trading-bot',
      description:
        'Automated Binance trading bot - Buy low/Sell high with stop loss limit/Trade multiple cryptocurrencies with Grid Trading',
      url: 'https://github.com/chrisleekr/binance-trading-bot',
    },
  },
  {
    rank: 11,
    username: 'HarshCasper',
    name: 'Harsh Mishra',
    url: 'https://github.com/HarshCasper',
    avatar: 'https://avatars.githubusercontent.com/u/47351025?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'Rotten-Scripts',
      description: 'Scripts that will make you go WOW😍💻',
      url: 'https://github.com/HarshCasper/Rotten-Scripts',
    },
  },
  {
    rank: 12,
    username: 'adeebshihadeh',
    name: 'Adeeb Shihadeh',
    url: 'https://github.com/adeebshihadeh',
    avatar: 'https://avatars.githubusercontent.com/u/8762862?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 13,
    username: 'jsuarezruiz',
    name: 'Javier Suárez',
    url: 'https://github.com/jsuarezruiz',
    avatar: 'https://avatars.githubusercontent.com/u/6755973?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'xamarin-forms-goodlooking-UI',
      description: 'Xamarin.Forms goodlooking UI samples',
      url: 'https://github.com/jsuarezruiz/xamarin-forms-goodlooking-UI',
    },
  },
  {
    rank: 14,
    username: 'lucidrains',
    name: 'Phil Wang',
    url: 'https://github.com/lucidrains',
    avatar: 'https://avatars.githubusercontent.com/u/108653?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'vit-pytorch',
      description:
        'Implementation of Vision Transformer, a simple way to achieve SOTA in vision classification with only a single transformer encoder, in Pytorch',
      url: 'https://github.com/lucidrains/vit-pytorch',
    },
  },
  {
    rank: 15,
    username: 'davidpdrsn',
    name: 'David Pedersen',
    url: 'https://github.com/davidpdrsn',
    avatar: 'https://avatars.githubusercontent.com/u/718941?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'todo-or-die',
      description: 'TODOs you cannot forget!',
      url: 'https://github.com/davidpdrsn/todo-or-die',
    },
  },
  {
    rank: 16,
    username: 'KATT',
    name: 'Alex Johansson',
    url: 'https://github.com/KATT',
    avatar: 'https://avatars.githubusercontent.com/u/459267?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'zart',
      description: '🤯zART-stack — Zero-API, React [Native], & TypeScript',
      url: 'https://github.com/KATT/zart',
    },
  },
  {
    rank: 17,
    username: 'PySimpleGUI',
    name: 'PySimpleGUI',
    url: 'https://github.com/PySimpleGUI',
    avatar: 'https://avatars.githubusercontent.com/u/46163555?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'PySimpleGUI',
      description:
        'Launched in 2018 Actively developed & supported. Supports tkinter, Qt, WxPython, Remi (in browser). Create custom GUI Windows simply, trivially with a full set of widgets. Multi-Window applications are also simple. Python 2.7 & 3 Support. 300+ Demo programs & Cookbook for rapid start. Extensive documentation. Examples using Machine Learning(GUI,…',
      url: 'https://github.com/PySimpleGUI/PySimpleGUI',
    },
  },
  {
    rank: 18,
    username: 'shuding',
    name: 'Shu Ding',
    url: 'https://github.com/shuding',
    avatar: 'https://avatars.githubusercontent.com/u/3676859?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'nextra',
      description: 'The Next.js Static Site Generator',
      url: 'https://github.com/shuding/nextra',
    },
  },
  {
    rank: 19,
    username: 'dtolnay',
    name: 'David Tolnay',
    url: 'https://github.com/dtolnay',
    avatar: 'https://avatars.githubusercontent.com/u/1940490?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'anyhow',
      description: 'Flexible concrete Error type built on std::error::Error',
      url: 'https://github.com/dtolnay/anyhow',
    },
  },
  {
    rank: 20,
    username: 'mokagio',
    name: 'Gio Lodi',
    url: 'https://github.com/mokagio',
    avatar: 'https://avatars.githubusercontent.com/u/1218433?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 21,
    username: 'lex111',
    name: 'Alexey Pyltsyn',
    url: 'https://github.com/lex111',
    avatar: 'https://avatars.githubusercontent.com/u/4408379?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'opensource.guide',
      description: 'Community guides for open source creators',
      url: 'https://github.com/lex111/opensource.guide',
    },
  },
  {
    rank: 22,
    username: 'vinitshahdeo',
    name: 'Vinit Shahdeo',
    url: 'https://github.com/vinitshahdeo',
    avatar: 'https://avatars.githubusercontent.com/u/20594326?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'Hacktoberfest2021',
      description:
        "A community-led mentorship initiative to help beginners kickstarting their open-source journey by completing Hacktoberfest'21 challenge | Curated list of beginner-friendly issues for Hacktoberfest 2021 | Raise PR to add your issues",
      url: 'https://github.com/vinitshahdeo/Hacktoberfest2021',
    },
  },
  {
    rank: 23,
    username: 'arvidn',
    name: 'Arvid Norberg',
    url: 'https://github.com/arvidn',
    avatar: 'https://avatars.githubusercontent.com/u/661450?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'libtorrent',
      description:
        'an efficient feature complete C++ bittorrent implementation',
      url: 'https://github.com/arvidn/libtorrent',
    },
  },
  {
    rank: 24,
    username: 'swharden',
    name: 'Scott W Harden',
    url: 'https://github.com/swharden',
    avatar: 'https://avatars.githubusercontent.com/u/4165489?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'Python-GUI-examples',
      description:
        'A growing collection of bare-bones GUI examples for python (PyQt4, Python 3)',
      url: 'https://github.com/swharden/Python-GUI-examples',
    },
  },
  {
    rank: 25,
    username: 'emilk',
    name: 'Emil Ernerfeldt',
    url: 'https://github.com/emilk',
    avatar: 'https://avatars.githubusercontent.com/u/1148717?s=96&v=4',
    since: 'daily',
    popularRepository: {
      repositoryName: 'egui',
      description: 'egui: an easy-to-use immediate mode GUI in pure Rust',
      url: 'https://github.com/emilk/egui',
    },
  },
];
