export const list = [
  {
    rank: 1,
    username: 'freeCodeCamp',
    repositoryName: 'freeCodeCamp',
    url: 'https://github.com/freeCodeCamp/freeCodeCamp',
    description:
      "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 331258,
    forks: 26648,
    starsSince: 322,
    since: 'daily',
    builtBy: [
      {
        username: 'QuincyLarson',
        url: 'https://github.com/QuincyLarson',
        avatar: 'https://avatars.githubusercontent.com/u/985197?s=40&v=4',
      },
      {
        username: 'raisedadead',
        url: 'https://github.com/raisedadead',
        avatar: 'https://avatars.githubusercontent.com/u/1884376?s=40&v=4',
      },
      {
        username: 'sahat',
        url: 'https://github.com/sahat',
        avatar: 'https://avatars.githubusercontent.com/u/544954?s=40&v=4',
      },
      {
        username: 'Bouncey',
        url: 'https://github.com/Bouncey',
        avatar: 'https://avatars.githubusercontent.com/u/18572518?s=40&v=4',
      },
      {
        username: 'terakilobyte',
        url: 'https://github.com/terakilobyte',
        avatar: 'https://avatars.githubusercontent.com/u/1911390?s=40&v=4',
      },
    ],
  },
  {
    rank: 2,
    username: 'authelia',
    repositoryName: 'authelia',
    url: 'https://github.com/authelia/authelia',
    description: 'The Single Sign-On Multi-Factor portal for web apps',
    language: 'Go',
    languageColor: '#00ADD8',
    totalStars: 9233,
    forks: 449,
    starsSince: 435,
    since: 'daily',
    builtBy: [
      {
        username: 'clems4ever',
        url: 'https://github.com/clems4ever',
        avatar: 'https://avatars.githubusercontent.com/u/3193257?s=40&v=4',
      },
      {
        username: 'apps/dependabot-preview',
        url: 'https://github.com/apps/dependabot-preview',
        avatar: 'https://avatars.githubusercontent.com/in/2141?s=40&v=4',
      },
      {
        username: 'nightah',
        url: 'https://github.com/nightah',
        avatar: 'https://avatars.githubusercontent.com/u/3339418?s=40&v=4',
      },
      {
        username: 'apps/renovate',
        url: 'https://github.com/apps/renovate',
        avatar: 'https://avatars.githubusercontent.com/in/2740?s=40&v=4',
      },
      {
        username: 'james-d-elliott',
        url: 'https://github.com/james-d-elliott',
        avatar: 'https://avatars.githubusercontent.com/u/3903683?s=40&v=4',
      },
    ],
  },
  {
    rank: 3,
    username: 'Richasy',
    repositoryName: 'Bili.Uwp',
    url: 'https://github.com/Richasy/Bili.Uwp',
    description: '适用于新系统UI的哔哩',
    language: 'C#',
    languageColor: '#178600',
    totalStars: 1079,
    forks: 66,
    starsSince: 240,
    since: 'daily',
    builtBy: [
      {
        username: 'Richasy',
        url: 'https://github.com/Richasy',
        avatar: 'https://avatars.githubusercontent.com/u/27713596?s=40&v=4',
      },
    ],
  },
  {
    rank: 4,
    username: 'jlevy',
    repositoryName: 'the-art-of-command-line',
    url: 'https://github.com/jlevy/the-art-of-command-line',
    description: 'Master the command line, in one page',
    language: null,
    languageColor: null,
    totalStars: 96296,
    forks: 10394,
    starsSince: 355,
    since: 'daily',
    builtBy: [
      {
        username: 'jlevy',
        url: 'https://github.com/jlevy',
        avatar: 'https://avatars.githubusercontent.com/u/2058167?s=40&v=4',
      },
      {
        username: 'petk',
        url: 'https://github.com/petk',
        avatar: 'https://avatars.githubusercontent.com/u/1614009?s=40&v=4',
      },
      {
        username: 'Psycho7',
        url: 'https://github.com/Psycho7',
        avatar: 'https://avatars.githubusercontent.com/u/8098452?s=40&v=4',
      },
      {
        username: 'stepan0904',
        url: 'https://github.com/stepan0904',
        avatar: 'https://avatars.githubusercontent.com/u/1155336?s=40&v=4',
      },
      {
        username: 'ericguirbal',
        url: 'https://github.com/ericguirbal',
        avatar: 'https://avatars.githubusercontent.com/u/322135?s=40&v=4',
      },
    ],
  },
  {
    rank: 5,
    username: 'aristocratos',
    repositoryName: 'btop',
    url: 'https://github.com/aristocratos/btop',
    description: 'A monitor of resources',
    language: 'C++',
    languageColor: '#f34b7d',
    totalStars: 448,
    forks: 14,
    starsSince: 93,
    since: 'daily',
    builtBy: [
      {
        username: 'aristocratos',
        url: 'https://github.com/aristocratos',
        avatar: 'https://avatars.githubusercontent.com/u/59659483?s=40&v=4',
      },
      {
        username: 'purinchu',
        url: 'https://github.com/purinchu',
        avatar: 'https://avatars.githubusercontent.com/u/30381288?s=40&v=4',
      },
    ],
  },
  {
    rank: 6,
    username: 'public-apis',
    repositoryName: 'public-apis',
    url: 'https://github.com/public-apis/public-apis',
    description: 'A collective list of free APIs',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 159455,
    forks: 18006,
    starsSince: 549,
    since: 'daily',
    builtBy: [
      {
        username: 'davemachado',
        url: 'https://github.com/davemachado',
        avatar: 'https://avatars.githubusercontent.com/u/15134885?s=40&v=4',
      },
      {
        username: 'matheusfelipeog',
        url: 'https://github.com/matheusfelipeog',
        avatar: 'https://avatars.githubusercontent.com/u/50463866?s=40&v=4',
      },
      {
        username: 'jbrooksuk',
        url: 'https://github.com/jbrooksuk',
        avatar: 'https://avatars.githubusercontent.com/u/246103?s=40&v=4',
      },
      {
        username: 'mikestreety',
        url: 'https://github.com/mikestreety',
        avatar: 'https://avatars.githubusercontent.com/u/354085?s=40&v=4',
      },
      {
        username: 'marekdano',
        url: 'https://github.com/marekdano',
        avatar: 'https://avatars.githubusercontent.com/u/1914165?s=40&v=4',
      },
    ],
  },
  {
    rank: 7,
    username: '30-seconds',
    repositoryName: '30-seconds-of-code',
    url: 'https://github.com/30-seconds/30-seconds-of-code',
    description:
      'Short JavaScript code snippets for all your development needs',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 85811,
    forks: 9069,
    starsSince: 175,
    since: 'daily',
    builtBy: [
      {
        username: 'Chalarangelo',
        url: 'https://github.com/Chalarangelo',
        avatar: 'https://avatars.githubusercontent.com/u/8281875?s=40&v=4',
      },
      {
        username: '30secondsofcode',
        url: 'https://github.com/30secondsofcode',
        avatar: 'https://avatars.githubusercontent.com/u/35068020?s=40&v=4',
      },
      {
        username: 'fejes713',
        url: 'https://github.com/fejes713',
        avatar: 'https://avatars.githubusercontent.com/u/25749162?s=40&v=4',
      },
      {
        username: 'kriadmin',
        url: 'https://github.com/kriadmin',
        avatar: 'https://avatars.githubusercontent.com/u/31792358?s=40&v=4',
      },
      {
        username: 'kingdavidmartins',
        url: 'https://github.com/kingdavidmartins',
        avatar: 'https://avatars.githubusercontent.com/u/10181183?s=40&v=4',
      },
    ],
  },
  {
    rank: 8,
    username: 'EddieHubCommunity',
    repositoryName: 'LinkFree',
    url: 'https://github.com/EddieHubCommunity/LinkFree',
    description: 'Open source alternative to LinkTree',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 134,
    forks: 122,
    starsSince: 6,
    since: 'daily',
    builtBy: [
      {
        username: 'eddiejaoude',
        url: 'https://github.com/eddiejaoude',
        avatar: 'https://avatars.githubusercontent.com/u/624760?s=40&v=4',
      },
      {
        username: 'FayasNoushad',
        url: 'https://github.com/FayasNoushad',
        avatar: 'https://avatars.githubusercontent.com/u/76828314?s=40&v=4',
      },
      {
        username: 'Flolight',
        url: 'https://github.com/Flolight',
        avatar: 'https://avatars.githubusercontent.com/u/9541039?s=40&v=4',
      },
      {
        username: 'Cahllagerfeld',
        url: 'https://github.com/Cahllagerfeld',
        avatar: 'https://avatars.githubusercontent.com/u/43843195?s=40&v=4',
      },
      {
        username: 'Panquesito7',
        url: 'https://github.com/Panquesito7',
        avatar: 'https://avatars.githubusercontent.com/u/51391473?s=40&v=4',
      },
    ],
  },
  {
    rank: 9,
    username: 'frontendbr',
    repositoryName: 'vagas',
    url: 'https://github.com/frontendbr/vagas',
    description: '🔬Espaço para divulgação de vagas para front-enders.',
    language: null,
    languageColor: null,
    totalStars: 7048,
    forks: 613,
    starsSince: 17,
    since: 'daily',
    builtBy: [
      {
        username: 'felipefialho',
        url: 'https://github.com/felipefialho',
        avatar: 'https://avatars.githubusercontent.com/u/3603793?s=40&v=4',
      },
      {
        username: 'fdaciuk',
        url: 'https://github.com/fdaciuk',
        avatar: 'https://avatars.githubusercontent.com/u/487669?s=40&v=4',
      },
      {
        username: 'diogomoretti',
        url: 'https://github.com/diogomoretti',
        avatar: 'https://avatars.githubusercontent.com/u/2853428?s=40&v=4',
      },
      {
        username: 'mtmr0x',
        url: 'https://github.com/mtmr0x',
        avatar: 'https://avatars.githubusercontent.com/u/5414299?s=40&v=4',
      },
      {
        username: 'Renato66',
        url: 'https://github.com/Renato66',
        avatar: 'https://avatars.githubusercontent.com/u/9284273?s=40&v=4',
      },
    ],
  },
  {
    rank: 10,
    username: 'kornia',
    repositoryName: 'kornia',
    url: 'https://github.com/kornia/kornia',
    description: 'Open Source Differentiable Computer Vision Library',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 4694,
    forks: 467,
    starsSince: 33,
    since: 'daily',
    builtBy: [
      {
        username: 'edgarriba',
        url: 'https://github.com/edgarriba',
        avatar: 'https://avatars.githubusercontent.com/u/5157099?s=40&v=4',
      },
      {
        username: 'ducha-aiki',
        url: 'https://github.com/ducha-aiki',
        avatar: 'https://avatars.githubusercontent.com/u/4803565?s=40&v=4',
      },
      {
        username: 'shijianjian',
        url: 'https://github.com/shijianjian',
        avatar: 'https://avatars.githubusercontent.com/u/15955486?s=40&v=4',
      },
      {
        username: 'dvd42',
        url: 'https://github.com/dvd42',
        avatar: 'https://avatars.githubusercontent.com/u/22733646?s=40&v=4',
      },
      {
        username: 'priba',
        url: 'https://github.com/priba',
        avatar: 'https://avatars.githubusercontent.com/u/16256646?s=40&v=4',
      },
    ],
  },
  {
    rank: 11,
    username: 'MicrosoftDocs',
    repositoryName: 'azure-docs',
    url: 'https://github.com/MicrosoftDocs/azure-docs',
    description: 'Open source documentation of Microsoft Azure',
    language: 'PowerShell',
    languageColor: '#012456',
    totalStars: 5828,
    forks: 14156,
    starsSince: 5,
    since: 'daily',
    builtBy: [
      {
        username: 'v-alje',
        url: 'https://github.com/v-alje',
        avatar: 'https://avatars.githubusercontent.com/u/4665434?s=40&v=4',
      },
      {
        username: 'ktoliver',
        url: 'https://github.com/ktoliver',
        avatar: 'https://avatars.githubusercontent.com/u/19416435?s=40&v=4',
      },
      {
        username: 'GitHubber17',
        url: 'https://github.com/GitHubber17',
        avatar: 'https://avatars.githubusercontent.com/u/28070425?s=40&v=4',
      },
      {
        username: 'TyNev',
        url: 'https://github.com/TyNev',
        avatar: 'https://avatars.githubusercontent.com/u/7462550?s=40&v=4',
      },
      {
        username: 'Juliako',
        url: 'https://github.com/Juliako',
        avatar: 'https://avatars.githubusercontent.com/u/1652984?s=40&v=4',
      },
    ],
  },
  {
    rank: 12,
    username: 'pittcsc',
    repositoryName: 'Summer2022-Internships',
    url: 'https://github.com/pittcsc/Summer2022-Internships',
    description: 'Collection of Summer 2022 tech internships!',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 6122,
    forks: 655,
    starsSince: 28,
    since: 'daily',
    builtBy: [
      {
        username: 'Zmwang622',
        url: 'https://github.com/Zmwang622',
        avatar: 'https://avatars.githubusercontent.com/u/36709118?s=40&v=4',
      },
      {
        username: 'GintasS',
        url: 'https://github.com/GintasS',
        avatar: 'https://avatars.githubusercontent.com/u/20372363?s=40&v=4',
      },
      {
        username: 'EParmar18',
        url: 'https://github.com/EParmar18',
        avatar: 'https://avatars.githubusercontent.com/u/44950492?s=40&v=4',
      },
      {
        username: 'ducdoan510',
        url: 'https://github.com/ducdoan510',
        avatar: 'https://avatars.githubusercontent.com/u/13146646?s=40&v=4',
      },
      {
        username: 'monishshah18',
        url: 'https://github.com/monishshah18',
        avatar: 'https://avatars.githubusercontent.com/u/40867596?s=40&v=4',
      },
    ],
  },
  {
    rank: 13,
    username: 'academind',
    repositoryName: 'react-complete-guide-code',
    url: 'https://github.com/academind/react-complete-guide-code',
    description:
      'Code snapshots and materials for our "React - The Complete Guide" course (https://acad.link/reactjs)',
    language: null,
    languageColor: null,
    totalStars: 1446,
    forks: 3374,
    starsSince: 8,
    since: 'daily',
    builtBy: [
      {
        username: 'maxschwarzmueller',
        url: 'https://github.com/maxschwarzmueller',
        avatar: 'https://avatars.githubusercontent.com/u/28806196?s=40&v=4',
      },
    ],
  },
  {
    rank: 14,
    username: 'freqtrade',
    repositoryName: 'freqtrade',
    url: 'https://github.com/freqtrade/freqtrade',
    description: 'Free, open source crypto trading bot',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 12167,
    forks: 2648,
    starsSince: 18,
    since: 'daily',
    builtBy: [
      {
        username: 'xmatthias',
        url: 'https://github.com/xmatthias',
        avatar: 'https://avatars.githubusercontent.com/u/5024695?s=40&v=4',
      },
      {
        username: 'hroff-1902',
        url: 'https://github.com/hroff-1902',
        avatar: 'https://avatars.githubusercontent.com/u/47309513?s=40&v=4',
      },
      {
        username: 'mishaker',
        url: 'https://github.com/mishaker',
        avatar: 'https://avatars.githubusercontent.com/u/939309?s=40&v=4',
      },
      {
        username: 'pyup-bot',
        url: 'https://github.com/pyup-bot',
        avatar: 'https://avatars.githubusercontent.com/u/16239342?s=40&v=4',
      },
      {
        username: 'vertti',
        url: 'https://github.com/vertti',
        avatar: 'https://avatars.githubusercontent.com/u/557751?s=40&v=4',
      },
    ],
  },
  {
    rank: 15,
    username: 'expo',
    repositoryName: 'expo',
    url: 'https://github.com/expo/expo',
    description:
      'An open-source platform for making universal native apps with React. Expo runs on Android, iOS, and the web.',
    language: 'Objective-C',
    languageColor: '#438eff',
    totalStars: 14920,
    forks: 2739,
    starsSince: 15,
    since: 'daily',
    builtBy: [
      {
        username: 'brentvatne',
        url: 'https://github.com/brentvatne',
        avatar: 'https://avatars.githubusercontent.com/u/90494?s=40&v=4',
      },
      {
        username: 'terribleben',
        url: 'https://github.com/terribleben',
        avatar: 'https://avatars.githubusercontent.com/u/1316332?s=40&v=4',
      },
      {
        username: 'sjchmiela',
        url: 'https://github.com/sjchmiela',
        avatar: 'https://avatars.githubusercontent.com/u/1151041?s=40&v=4',
      },
      {
        username: 'esamelson',
        url: 'https://github.com/esamelson',
        avatar: 'https://avatars.githubusercontent.com/u/19958240?s=40&v=4',
      },
      {
        username: 'tsapeta',
        url: 'https://github.com/tsapeta',
        avatar: 'https://avatars.githubusercontent.com/u/1714764?s=40&v=4',
      },
    ],
  },
  {
    rank: 16,
    username: 'DovAmir',
    repositoryName: 'awesome-design-patterns',
    url: 'https://github.com/DovAmir/awesome-design-patterns',
    description:
      'A curated list of software and architecture related design patterns.',
    language: null,
    languageColor: null,
    totalStars: 14628,
    forks: 1230,
    starsSince: 206,
    since: 'daily',
    builtBy: [
      {
        username: 'DovAmir',
        url: 'https://github.com/DovAmir',
        avatar: 'https://avatars.githubusercontent.com/u/2938156?s=40&v=4',
      },
      {
        username: 'LeoColomb',
        url: 'https://github.com/LeoColomb',
        avatar: 'https://avatars.githubusercontent.com/u/846943?s=40&v=4',
      },
      {
        username: 'arocks',
        url: 'https://github.com/arocks',
        avatar: 'https://avatars.githubusercontent.com/u/48323?s=40&v=4',
      },
      {
        username: 'ribaricplusplus',
        url: 'https://github.com/ribaricplusplus',
        avatar: 'https://avatars.githubusercontent.com/u/43731400?s=40&v=4',
      },
      {
        username: 'chihab',
        url: 'https://github.com/chihab',
        avatar: 'https://avatars.githubusercontent.com/u/196852?s=40&v=4',
      },
    ],
  },
  {
    rank: 17,
    username: 'pedroslopez',
    repositoryName: 'whatsapp-web.js',
    url: 'https://github.com/pedroslopez/whatsapp-web.js',
    description:
      'A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 3476,
    forks: 859,
    starsSince: 10,
    since: 'daily',
    builtBy: [
      {
        username: 'pedroslopez',
        url: 'https://github.com/pedroslopez',
        avatar: 'https://avatars.githubusercontent.com/u/4368928?s=40&v=4',
      },
      {
        username: 'Aliyss',
        url: 'https://github.com/Aliyss',
        avatar: 'https://avatars.githubusercontent.com/u/33941859?s=40&v=4',
      },
      {
        username: 'stefanfuchs',
        url: 'https://github.com/stefanfuchs',
        avatar: 'https://avatars.githubusercontent.com/u/3092650?s=40&v=4',
      },
      {
        username: 'tuyuribr',
        url: 'https://github.com/tuyuribr',
        avatar: 'https://avatars.githubusercontent.com/u/45042245?s=40&v=4',
      },
      {
        username: 'caioagiani',
        url: 'https://github.com/caioagiani',
        avatar: 'https://avatars.githubusercontent.com/u/56451511?s=40&v=4',
      },
    ],
  },
  {
    rank: 18,
    username: 'LeCoupa',
    repositoryName: 'awesome-cheatsheets',
    url: 'https://github.com/LeCoupa/awesome-cheatsheets',
    description:
      '👩‍💻👨‍💻Awesome cheatsheets for popular programming languages, frameworks and development tools. They include everything you should know in one single file.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 23326,
    forks: 3811,
    starsSince: 180,
    since: 'daily',
    builtBy: [
      {
        username: 'LeCoupa',
        url: 'https://github.com/LeCoupa',
        avatar: 'https://avatars.githubusercontent.com/u/1658644?s=40&v=4',
      },
      {
        username: 'yogeshojha',
        url: 'https://github.com/yogeshojha',
        avatar: 'https://avatars.githubusercontent.com/u/17223002?s=40&v=4',
      },
      {
        username: 'kobus1998',
        url: 'https://github.com/kobus1998',
        avatar: 'https://avatars.githubusercontent.com/u/17469908?s=40&v=4',
      },
      {
        username: 'thewolfcommander',
        url: 'https://github.com/thewolfcommander',
        avatar: 'https://avatars.githubusercontent.com/u/38884133?s=40&v=4',
      },
      {
        username: 'Alexound',
        url: 'https://github.com/Alexound',
        avatar: 'https://avatars.githubusercontent.com/u/22021219?s=40&v=4',
      },
    ],
  },
  {
    rank: 19,
    username: 'cipher387',
    repositoryName: 'Dorks-collections-list',
    url: 'https://github.com/cipher387/Dorks-collections-list',
    description:
      'List of Github repositories and articles with list of dorks for different search engines',
    language: null,
    languageColor: null,
    totalStars: 227,
    forks: 19,
    starsSince: 47,
    since: 'daily',
    builtBy: [
      {
        username: 'cipher387',
        url: 'https://github.com/cipher387',
        avatar: 'https://avatars.githubusercontent.com/u/66636466?s=40&v=4',
      },
    ],
  },
  {
    rank: 20,
    username: 'frappe',
    repositoryName: 'frappe',
    url: 'https://github.com/frappe/frappe',
    description:
      'Low code web framework for real world applications, in Python and Javascript',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 2935,
    forks: 1780,
    starsSince: 42,
    since: 'daily',
    builtBy: [
      {
        username: 'rmehta',
        url: 'https://github.com/rmehta',
        avatar: 'https://avatars.githubusercontent.com/u/140076?s=40&v=4',
      },
      {
        username: 'surajshetty3416',
        url: 'https://github.com/surajshetty3416',
        avatar: 'https://avatars.githubusercontent.com/u/13928957?s=40&v=4',
      },
      {
        username: 'anandpdoshi',
        url: 'https://github.com/anandpdoshi',
        avatar: 'https://avatars.githubusercontent.com/u/836785?s=40&v=4',
      },
      {
        username: 'nabinhait',
        url: 'https://github.com/nabinhait',
        avatar: 'https://avatars.githubusercontent.com/u/836784?s=40&v=4',
      },
      {
        username: 'netchampfaris',
        url: 'https://github.com/netchampfaris',
        avatar: 'https://avatars.githubusercontent.com/u/9355208?s=40&v=4',
      },
    ],
  },
  {
    rank: 21,
    username: 'denysdovhan',
    repositoryName: 'wtfjs',
    url: 'https://github.com/denysdovhan/wtfjs',
    description: '🤪A list of funny and tricky JavaScript examples',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 23550,
    forks: 1605,
    starsSince: 40,
    since: 'daily',
    builtBy: [
      {
        username: 'denysdovhan',
        url: 'https://github.com/denysdovhan',
        avatar: 'https://avatars.githubusercontent.com/u/3459374?s=40&v=4',
      },
      {
        username: 'mbiesiad',
        url: 'https://github.com/mbiesiad',
        avatar: 'https://avatars.githubusercontent.com/u/18367606?s=40&v=4',
      },
      {
        username: 'semantic-release-bot',
        url: 'https://github.com/semantic-release-bot',
        avatar: 'https://avatars.githubusercontent.com/u/32174276?s=40&v=4',
      },
      {
        username: 'eritbh',
        url: 'https://github.com/eritbh',
        avatar: 'https://avatars.githubusercontent.com/u/4165301?s=40&v=4',
      },
      {
        username: 'pero5ar',
        url: 'https://github.com/pero5ar',
        avatar: 'https://avatars.githubusercontent.com/u/15316407?s=40&v=4',
      },
    ],
  },
  {
    rank: 22,
    username: 'typescript-cheatsheets',
    repositoryName: 'react',
    url: 'https://github.com/typescript-cheatsheets/react',
    description:
      'Cheatsheets for experienced React developers getting started with TypeScript',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    totalStars: 28547,
    forks: 2213,
    starsSince: 232,
    since: 'daily',
    builtBy: [
      {
        username: 'sw-yx',
        url: 'https://github.com/sw-yx',
        avatar: 'https://avatars.githubusercontent.com/u/6764957?s=40&v=4',
      },
      {
        username: 'apps/prettifier',
        url: 'https://github.com/apps/prettifier',
        avatar: 'https://avatars.githubusercontent.com/in/21352?s=40&v=4',
      },
      {
        username: 'apps/github-actions',
        url: 'https://github.com/apps/github-actions',
        avatar: 'https://avatars.githubusercontent.com/in/15368?s=40&v=4',
      },
      {
        username: 'apps/allcontributors',
        url: 'https://github.com/apps/allcontributors',
        avatar: 'https://avatars.githubusercontent.com/in/23186?s=40&v=4',
      },
      {
        username: 'eps1lon',
        url: 'https://github.com/eps1lon',
        avatar: 'https://avatars.githubusercontent.com/u/12292047?s=40&v=4',
      },
    ],
  },
  {
    rank: 23,
    username: 'mlflow',
    repositoryName: 'mlflow',
    url: 'https://github.com/mlflow/mlflow',
    description: 'Open source platform for the machine learning lifecycle',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 10180,
    forks: 2268,
    starsSince: 5,
    since: 'daily',
    builtBy: [
      {
        username: 'harupy',
        url: 'https://github.com/harupy',
        avatar: 'https://avatars.githubusercontent.com/u/17039389?s=40&v=4',
      },
      {
        username: 'dbczumar',
        url: 'https://github.com/dbczumar',
        avatar: 'https://avatars.githubusercontent.com/u/39497902?s=40&v=4',
      },
      {
        username: 'smurching',
        url: 'https://github.com/smurching',
        avatar: 'https://avatars.githubusercontent.com/u/2358483?s=40&v=4',
      },
      {
        username: 'aarondav',
        url: 'https://github.com/aarondav',
        avatar: 'https://avatars.githubusercontent.com/u/1400247?s=40&v=4',
      },
      {
        username: 'tomasatdatabricks',
        url: 'https://github.com/tomasatdatabricks',
        avatar: 'https://avatars.githubusercontent.com/u/33237569?s=40&v=4',
      },
    ],
  },
  {
    rank: 24,
    username: 'juice-shop',
    repositoryName: 'juice-shop',
    url: 'https://github.com/juice-shop/juice-shop',
    description:
      'OWASP Juice Shop: Probably the most modern and sophisticated insecure web application',
    language: 'TypeScript',
    languageColor: '#2b7489',
    totalStars: 5186,
    forks: 3629,
    starsSince: 4,
    since: 'daily',
    builtBy: [
      {
        username: 'bkimminich',
        url: 'https://github.com/bkimminich',
        avatar: 'https://avatars.githubusercontent.com/u/3531020?s=40&v=4',
      },
      {
        username: 'J12934',
        url: 'https://github.com/J12934',
        avatar: 'https://avatars.githubusercontent.com/u/13718901?s=40&v=4',
      },
      {
        username: 'Aashish683',
        url: 'https://github.com/Aashish683',
        avatar: 'https://avatars.githubusercontent.com/u/30633088?s=40&v=4',
      },
      {
        username: 'apps/greenkeeper',
        url: 'https://github.com/apps/greenkeeper',
        avatar: 'https://avatars.githubusercontent.com/in/505?s=40&v=4',
      },
      {
        username: 'MarcRler',
        url: 'https://github.com/MarcRler',
        avatar: 'https://avatars.githubusercontent.com/u/18336861?s=40&v=4',
      },
    ],
  },
  {
    rank: 25,
    username: 'samuelcolvin',
    repositoryName: 'pydantic',
    url: 'https://github.com/samuelcolvin/pydantic',
    description: 'Data parsing and validation using Python type hints',
    language: 'Python',
    languageColor: '#3572A5',
    totalStars: 7549,
    forks: 681,
    starsSince: 6,
    since: 'daily',
    builtBy: [
      {
        username: 'samuelcolvin',
        url: 'https://github.com/samuelcolvin',
        avatar: 'https://avatars.githubusercontent.com/u/4039449?s=40&v=4',
      },
      {
        username: 'PrettyWood',
        url: 'https://github.com/PrettyWood',
        avatar: 'https://avatars.githubusercontent.com/u/18406791?s=40&v=4',
      },
      {
        username: 'apps/dependabot-preview',
        url: 'https://github.com/apps/dependabot-preview',
        avatar: 'https://avatars.githubusercontent.com/in/2141?s=40&v=4',
      },
      {
        username: 'pyup-bot',
        url: 'https://github.com/pyup-bot',
        avatar: 'https://avatars.githubusercontent.com/u/16239342?s=40&v=4',
      },
      {
        username: 'apps/dependabot',
        url: 'https://github.com/apps/dependabot',
        avatar: 'https://avatars.githubusercontent.com/in/29110?s=40&v=4',
      },
    ],
  },
];
